Optional value unwrap crash fix
When deploying this swift package in a Docker container, `NSClassFromString("__NSCFString")` returns `nil` and causes the crash.
`Regex/Utilities.swift:26: Fatal error: Unexpectedly found nil while unwrapping an Optional value`